### ISSUE TITLE
hardcoded fifo path . 

### ISSUE THREAD

**Issue by naushit** [asipto/kamcli#1]
I can't get it to work,  for some reason, even if I change fifo path in /etc/kamcli/kamcli.ini , it keeps going to /var/run/kamailio. 

[root@cloud2 kamcli]# cat /etc/kamcli/kamcli.ini
[main]
domain=test.com

[db]
type=mysql
driver=mysqldb
host=localhost
dbname=kamailio
rwuser=kamailio
rwpassword=kamailiorw
rouser=kamailio
ropassword=kamailiorw
rwurl=%(type)s+%(driver)s://%(rwuser)s:%(rwpassword)s@%(host)s/%(dbname)s
rourl=%(type)s+%(driver)s://%(rouser)s:%(ropassword)s@%(host)s/%(dbname)s

[ctl]
type=mi

[mi]
transport=fifo
path=/tmp/kamailio_fifo
rplnamebase=kamailio_fifo_reply
rpldir=/tmp

[jsonrpc]
transport=fifo
path=/tmp/kamailio_jsonrpc_fifo
rplnamebase=kamailio_json_fifo_reply
rpldir=/tmp
[root@cloud2 kamcli]#

[root@cloud2 kamcli]# kamcli -v --config=kamcli/kamcli.ini stats
Starting to wait for reply on: /tmp/kamailio_fifo_reply

Traceback (most recent call last):
  File "/usr/bin/kamcli", line 9, in <module>
    load_entry_point('kamcli==1.0', 'console_scripts', 'kamcli')()
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/kamcli-1.0-py2.6.egg/kamcli/commands/cmd_stats.py", line 36, in cli
    command_ctl(ctx, 'get_statistics', [ 'all' ])
  File "/usr/lib/python2.6/site-packages/kamcli-1.0-py2.6.egg/kamcli/iorpc.py", line 186, in command_ctl
    "kamailio_fifo_reply", "raw", cmd, params)
  File "/usr/lib/python2.6/site-packages/kamcli-1.0-py2.6.egg/kamcli/iorpc.py", line 91, in command_mi_fifo
    w = os.open(sndpath, os.O_WRONLY)
OSError: [Errno 2] No such file or directory: '/var/run/kamailio/kamailio_fifo'

**Comment by miconda** [comment]
Thanks for the report. I pushed a patch that should fix it: 3baabf03eda042b3c9d3c6e6281f0113c237551c

Didn't have the time to try it, if the issue is still there, reopen this item.
